# Copyright (C) 2023 CERN for the benefit of the ATLAS collaboration

# Use a specific version of the analysisbase image for development.
FROM gitlab-registry.cern.ch/atlas/athena/analysisbase:24.2.24

# Start the image simply with bash.
CMD /bin/bash
